//! System tray integration.
//!
//! macOS has no "tray" in the Windows sense — the equivalent is a menu-bar
//! status item ([`NSStatusItem`]), which is what `TrayIcon` maps to. Three
//! things live here:
//!
//! 1. **Playback info** — shown *in the menu*, not next to the icon. A
//!    persistent menu-bar title eats a variable slice of the menu bar and
//!    shoves other apps' status items around, and live stream titles are long
//!    enough to make that obvious. The status item is icon-only; clicking it
//!    opens the menu, whose first row carries the streamer and title. The
//!    tooltip carries the full text for hover.
//! 2. **Transport controls** — play/pause and mute menu items. The media
//!    element lives in the webview, so these only emit events; the player
//!    performs the action.
//! 3. **Background residency** — the tray is the anchor that keeps the app
//!    alive once the window is hidden (see `lib.rs` close-to-tray handling),
//!    which is what makes background playback possible at all.
//!
//! The tray icon is a *template* image (`icon_as_template`): macOS paints it
//! with the current menu-bar foreground colour using only the alpha channel,
//! so `icons/tray-icon.png` is a monochrome silhouette rather than the
//! full-colour app icon.

use std::sync::Mutex;

use tauri::{
    image::Image,
    menu::{Menu, MenuItem, PredefinedMenuItem},
    tray::TrayIconBuilder,
    AppHandle, Emitter, Manager, Runtime, State, Wry,
};

/// Id used to look the tray icon back up at runtime.
pub const TRAY_ID: &str = "main";

const MENU_SHOW: &str = "tray_show";
const MENU_TOGGLE_PLAY: &str = "tray_toggle_play";
const MENU_TOGGLE_MUTE: &str = "tray_toggle_mute";
const MENU_QUIT: &str = "tray_quit";

/// Emitted to the webview when the user picks a transport item from the tray
/// menu. The player owns the media element, so it performs the actual action.
pub const EVENT_TOGGLE_PLAY: &str = "tray://toggle-play";
pub const EVENT_TOGGLE_MUTE: &str = "tray://toggle-mute";

/// A menu is a dropdown, so it can afford far more text than the menu bar —
/// but not an unbounded amount, or a pathological title makes the menu wider
/// than the screen. The tooltip carries the untruncated text.
const MENU_TITLE_MAX_CHARS: usize = 48;

/// Monochrome silhouette, generated by `icons/gen_tray_icon.py`.
const TRAY_ICON_PNG: &[u8] = include_bytes!("../icons/tray-icon.png");

// ── Now-playing model ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default)]
struct NowPlaying {
    title: Option<String>,
    streamer: Option<String>,
    playing: bool,
    muted: bool,
}

impl NowPlaying {
    fn is_active(&self) -> bool {
        self.title.as_deref().is_some_and(|t| !t.trim().is_empty())
    }

    /// First row of the menu. Empty state gets a placeholder so the menu never
    /// opens with a blank first line.
    fn menu_label(&self) -> String {
        if !self.is_active() {
            return "未在播放".to_string();
        }
        let title = self.title.as_deref().unwrap_or_default();
        let glyph = if self.playing { "▶" } else { "⏸" };
        let body = match self.streamer.as_deref().filter(|s| !s.trim().is_empty()) {
            Some(streamer) => format!("{streamer} · {title}"),
            None => title.to_string(),
        };
        format!("{glyph} {}", truncate(&body, MENU_TITLE_MAX_CHARS))
    }

    fn tooltip(&self) -> String {
        if !self.is_active() {
            return "Streaming".to_string();
        }
        let title = self.title.as_deref().unwrap_or_default();
        let state = if self.playing { "播放中" } else { "已暂停" };
        match self.streamer.as_deref().filter(|s| !s.trim().is_empty()) {
            Some(streamer) => format!("Streaming\n{streamer} · {title}\n{state}"),
            None => format!("Streaming\n{title}\n{state}"),
        }
    }
}

/// Truncates on character boundaries (not bytes) so CJK titles are safe.
fn truncate(s: &str, max_chars: usize) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if i >= max_chars {
            out.push('…');
            break;
        }
        out.push(ch);
    }
    out
}

/// Tray-owned state. The menu item handles are kept so their labels can be
/// flipped between 播放/暂停 and 静音/取消静音 without rebuilding the menu.
#[derive(Default)]
pub struct TrayState {
    now_playing: Mutex<NowPlaying>,
    header_item: Mutex<Option<MenuItem<Wry>>>,
    play_item: Mutex<Option<MenuItem<Wry>>>,
    mute_item: Mutex<Option<MenuItem<Wry>>>,
}

// ── Rendering ────────────────────────────────────────────────────────────────

fn apply(app: &AppHandle<Wry>, state: &TrayState, np: &NowPlaying) {
    if let Some(tray) = app.tray_by_id(TRAY_ID) {
        if let Err(e) = tray.set_tooltip(Some(np.tooltip())) {
            tracing::warn!("tray set_tooltip failed: {e}");
        }
    }

    let active = np.is_active();
    if let Ok(guard) = state.header_item.lock() {
        if let Some(item) = guard.as_ref() {
            let _ = item.set_text(np.menu_label());
        }
    }
    if let Ok(guard) = state.play_item.lock() {
        if let Some(item) = guard.as_ref() {
            let _ = item.set_text(if np.playing { "暂停" } else { "播放" });
            let _ = item.set_enabled(active);
        }
    }
    if let Ok(guard) = state.mute_item.lock() {
        if let Some(item) = guard.as_ref() {
            let _ = item.set_text(if np.muted { "取消静音" } else { "静音" });
            let _ = item.set_enabled(active);
        }
    }
}

// ── Window helpers ───────────────────────────────────────────────────────────

/// Brings the main window back from hidden/minimised and focuses it.
fn show_main_window<R: Runtime>(app: &AppHandle<R>) {
    // On macOS the whole app (not just the window) can be hidden; unhide it
    // first or the window stays invisible behind `NSApp.hide`.
    #[cfg(target_os = "macos")]
    let _ = app.show();

    if let Some(win) = app.get_webview_window("main") {
        let _ = win.unminimize();
        let _ = win.show();
        let _ = win.set_focus();
    }
}

// ── Setup ────────────────────────────────────────────────────────────────────

/// Builds the tray icon. Called once from the app `setup` hook.
pub fn init(app: &AppHandle<Wry>) -> tauri::Result<()> {
    // Disabled, purely informational: it is the first thing the user sees when
    // they click the icon, which is where playback info belongs.
    let header = MenuItem::with_id(app, "tray_header", "未在播放", false, None::<&str>)?;
    let show = MenuItem::with_id(app, MENU_SHOW, "显示主窗口", true, None::<&str>)?;
    let toggle_play = MenuItem::with_id(app, MENU_TOGGLE_PLAY, "播放", false, None::<&str>)?;
    let toggle_mute = MenuItem::with_id(app, MENU_TOGGLE_MUTE, "静音", false, None::<&str>)?;
    let quit = MenuItem::with_id(app, MENU_QUIT, "退出 Streaming", true, None::<&str>)?;

    let menu = Menu::with_items(
        app,
        &[
            &header,
            &PredefinedMenuItem::separator(app)?,
            &show,
            &toggle_play,
            &toggle_mute,
            &PredefinedMenuItem::separator(app)?,
            &quit,
        ],
    )?;

    let mut builder = TrayIconBuilder::with_id(TRAY_ID)
        .icon(Image::from_bytes(TRAY_ICON_PNG)?)
        .tooltip("Streaming")
        .menu(&menu)
        // Left click opens the menu, so clicking the icon is what reveals the
        // playback info. The window comes back via 显示主窗口.
        .show_menu_on_left_click(true)
        .on_menu_event(|app, event| match event.id().as_ref() {
            MENU_SHOW => show_main_window(app),
            MENU_TOGGLE_PLAY => {
                let _ = app.emit(EVENT_TOGGLE_PLAY, ());
            }
            MENU_TOGGLE_MUTE => {
                let _ = app.emit(EVENT_TOGGLE_MUTE, ());
            }
            MENU_QUIT => app.exit(0),
            _ => {}
        });

    // Template rendering keeps the glyph legible on both light and dark menu
    // bars. macOS-only; a no-op elsewhere.
    #[cfg(target_os = "macos")]
    {
        builder = builder.icon_as_template(true);
    }

    let tray = builder.build(app)?;

    // Belt and braces: never carry a menu-bar title. A leftover title from an
    // earlier build would keep stealing menu-bar width.
    let _ = tray.set_title(None::<String>);

    let state = app.state::<TrayState>();
    if let Ok(mut guard) = state.header_item.lock() {
        *guard = Some(header);
    }
    if let Ok(mut guard) = state.play_item.lock() {
        *guard = Some(toggle_play);
    }
    if let Ok(mut guard) = state.mute_item.lock() {
        *guard = Some(toggle_mute);
    }

    tracing::info!("tray icon created (id={TRAY_ID})");
    Ok(())
}

// ── Commands ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NowPlayingUpdate {
    pub title: String,
    #[serde(default)]
    pub streamer: Option<String>,
    #[serde(default)]
    pub playing: bool,
    #[serde(default)]
    pub muted: bool,
}

/// Pushes the current playback metadata into the tray menu / tooltip.
#[tauri::command]
pub fn set_now_playing(
    app: AppHandle<Wry>,
    state: State<'_, TrayState>,
    update: NowPlayingUpdate,
) -> Result<(), String> {
    let np = NowPlaying {
        title: Some(update.title),
        streamer: update.streamer,
        playing: update.playing,
        muted: update.muted,
    };
    if let Ok(mut guard) = state.now_playing.lock() {
        *guard = np.clone();
    }
    apply(&app, &state, &np);
    Ok(())
}

/// Clears the playback info — call when playback stops or the player unmounts.
#[tauri::command]
pub fn clear_now_playing(app: AppHandle<Wry>, state: State<'_, TrayState>) -> Result<(), String> {
    let np = NowPlaying::default();
    if let Ok(mut guard) = state.now_playing.lock() {
        *guard = np.clone();
    }
    apply(&app, &state, &np);
    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn np(title: Option<&str>, streamer: Option<&str>, playing: bool) -> NowPlaying {
        NowPlaying {
            title: title.map(str::to_string),
            streamer: streamer.map(str::to_string),
            playing,
            muted: false,
        }
    }

    #[test]
    fn idle_menu_shows_a_placeholder() {
        assert_eq!(np(None, None, false).menu_label(), "未在播放");
        assert_eq!(np(Some(""), None, false).menu_label(), "未在播放");
        assert_eq!(np(Some("   "), None, false).menu_label(), "未在播放");
        assert_eq!(np(None, None, false).tooltip(), "Streaming");
    }

    #[test]
    fn menu_label_carries_streamer_title_and_state() {
        assert_eq!(
            np(Some("五五开"), Some("主播"), true).menu_label(),
            "▶ 主播 · 五五开"
        );
        assert_eq!(
            np(Some("五五开"), Some("主播"), false).menu_label(),
            "⏸ 主播 · 五五开"
        );
        // No streamer: just the title.
        assert_eq!(np(Some("五五开"), None, true).menu_label(), "▶ 五五开");
    }

    #[test]
    fn long_titles_are_truncated_on_char_boundaries() {
        let long = "这是一个非常非常长的直播间标题用来测试截断逻辑是否正确工作以及是否会在字符边界上安全地截断而不是把某个汉字切成两半";
        let label = np(Some(long), None, true).menu_label();
        let body = label.strip_prefix("▶ ").unwrap();
        assert_eq!(body.chars().count(), MENU_TITLE_MAX_CHARS + 1); // + ellipsis
        assert!(body.ends_with('…'));
        // Must remain valid UTF-8 after slicing a CJK string.
        assert_eq!(
            body.chars().take(MENU_TITLE_MAX_CHARS).collect::<String>(),
            long.chars().take(MENU_TITLE_MAX_CHARS).collect::<String>()
        );
    }

    #[test]
    fn short_titles_are_untouched() {
        assert_eq!(np(Some("五五开"), None, true).menu_label(), "▶ 五五开");
    }

    #[test]
    fn tooltip_carries_streamer_and_state() {
        let tip = np(Some("标题"), Some("主播"), true).tooltip();
        assert!(tip.contains("主播"));
        assert!(tip.contains("标题"));
        assert!(tip.contains("播放中"));

        let paused = np(Some("标题"), None, false).tooltip();
        assert!(paused.contains("已暂停"));
    }
}
